stages:
  - build
  - deploy

# Build stage: Install dependencies and run build command with caching
build_job:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  only:
    - main # Run this job only on the 'main' branch

# Deploy stage: Deploy the application
deploy_job:
  stage: deploy
  script:
    - npm run deploy
  only:
    - main # Deploy only from the 'main' branch
