name: CI Pipeline

# Trigger the workflow only on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    # Use the latest Ubuntu version as the runner
    runs-on: ubuntu-latest

    # Cache 'node_modules' between builds to speed up the process
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your Node.js version

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

  deploy:
    # Deploy only if the build job succeeds
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Ensure you're using the correct Node.js version

      - name: Install dependencies
        run: npm install

      - name: Deploy the application
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
